import {
  Home, Users, Calendar, CalendarDays, ClipboardList, ClipboardCheck, CheckSquare,
  Settings, Wrench, BookOpen, GraduationCap, Bot, BarChart3, Building2,
  MessageSquare, Bell, Megaphone, Wallet, Clock, QrCode, Package,
  DollarSign, FileText, ShoppingCart, Store, Star, AlertTriangle,
  Briefcase, Factory, Shield, UserCheck, Headphones, Calculator,
  FolderKanban, MapPin, Coffee, Truck, Search, User, Database
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type NavScope = "branch" | "hq" | "factory";

export type NavGroupId = "operations" | "management" | "settings";

export interface NavGroup {
  id: NavGroupId;
  labelKey: string;
  defaultLabelTR: string;
  defaultLabelEN: string;
  order: number;
}

export interface NavItem {
  id: string;
  route: string;
  icon: LucideIcon;
  group: NavGroupId;
  order: number;
  labelKey: string;
  defaultLabelTR: string;
  defaultLabelEN: string;
  scopes: NavScope[];
  roles?: string[];
  color?: string;
  bgColor?: string;
  descriptionKey?: string;
  defaultDescTR?: string;
  defaultDescEN?: string;
  badge?: string;
  getRoute?: (user: any) => string;
  isSearch?: boolean;
}

export const NAV_GROUPS: NavGroup[] = [
  { id: "operations", labelKey: "nav.group.operations", defaultLabelTR: "Operasyon", defaultLabelEN: "Operations", order: 1 },
  { id: "management", labelKey: "nav.group.management", defaultLabelTR: "Yönetim & Denetim", defaultLabelEN: "Management & Oversight", order: 2 },
  { id: "settings", labelKey: "nav.group.settings", defaultLabelTR: "Ayarlar & Destek", defaultLabelEN: "Settings & Support", order: 3 },
];

export const NAV_ITEMS: NavItem[] = [
  {
    id: "home",
    route: "/",
    icon: Home,
    group: "operations",
    order: 0,
    labelKey: "nav.home",
    defaultLabelTR: "Ana Sayfa",
    defaultLabelEN: "Home",
    scopes: ["branch", "hq", "factory"],
    getRoute: (user) => {
      if (user?.role === "ceo") return "/ceo-command-center";
      if (user?.role === "cgo") return "/cgo-command-center";
      return "/";
    },
  },
  {
    id: "tasks",
    route: "/gorevler",
    icon: ClipboardList,
    group: "operations",
    order: 10,
    labelKey: "nav.tasks",
    defaultLabelTR: "Görevler",
    defaultLabelEN: "Tasks",
    scopes: ["branch", "hq", "factory"],
    color: "bg-green-500",
    bgColor: "bg-blue-100 dark:bg-blue-900/40",
    badge: "pendingTasks",
    descriptionKey: "nav.desc.tasks",
    defaultDescTR: "Günlük işler",
    defaultDescEN: "Daily tasks",
  },
  {
    id: "pending-checks",
    route: "/gorevler?status=kontrol_bekliyor",
    icon: UserCheck,
    group: "operations",
    order: 11,
    labelKey: "nav.pendingChecks",
    defaultLabelTR: "Bekleyen Kontroller",
    defaultLabelEN: "Pending Reviews",
    scopes: ["branch"],
    roles: ["supervisor", "supervisor_buddy"],
    color: "bg-amber-500",
    badge: "pendingChecks",
    descriptionKey: "nav.desc.pendingChecks",
    defaultDescTR: "Kontrol bekleyen görevler",
    defaultDescEN: "Tasks awaiting review",
  },
  {
    id: "checklists",
    route: "/checklistler",
    icon: ClipboardCheck,
    group: "operations",
    order: 12,
    labelKey: "nav.checklists",
    defaultLabelTR: "Kontrol Listeleri",
    defaultLabelEN: "Checklists",
    scopes: ["branch"],
    color: "bg-teal-500",
    bgColor: "bg-emerald-100 dark:bg-emerald-900/40",
    descriptionKey: "nav.desc.checklists",
    defaultDescTR: "Günlük kontroller",
    defaultDescEN: "Daily checklists",
  },
  {
    id: "checklists-hq",
    route: "/yonetim/checklistler",
    icon: CheckSquare,
    group: "operations",
    order: 12,
    labelKey: "nav.checklistsHQ",
    defaultLabelTR: "Checklistler",
    defaultLabelEN: "Checklists",
    scopes: ["hq"],
    color: "bg-teal-500",
    descriptionKey: "nav.desc.checklistsHQ",
    defaultDescTR: "Checklist yönetimi",
    defaultDescEN: "Checklist management",
  },
  {
    id: "faults",
    route: "/ariza",
    icon: Wrench,
    group: "operations",
    order: 15,
    labelKey: "nav.faults",
    defaultLabelTR: "Arızalar",
    defaultLabelEN: "Faults",
    scopes: ["branch", "hq"],
    color: "bg-orange-500",
    badge: "openFaults",
    descriptionKey: "nav.desc.faults",
    defaultDescTR: "Ekipman sorunları",
    defaultDescEN: "Equipment issues",
  },
  {
    id: "equipment",
    route: "/ekipman",
    icon: Coffee,
    group: "operations",
    order: 16,
    labelKey: "nav.equipment",
    defaultLabelTR: "Ekipman",
    defaultLabelEN: "Equipment",
    scopes: ["branch", "hq"],
    color: "bg-amber-600",
    descriptionKey: "nav.desc.equipment",
    defaultDescTR: "Ekipman yönetimi",
    defaultDescEN: "Equipment management",
  },
  {
    id: "lost-found",
    route: "/kayip-esya",
    icon: Briefcase,
    group: "operations",
    order: 18,
    labelKey: "nav.lostFound",
    defaultLabelTR: "Kayıp Eşya",
    defaultLabelEN: "Lost & Found",
    scopes: ["branch"],
    color: "bg-yellow-600",
    descriptionKey: "nav.desc.lostFound",
    defaultDescTR: "Bulunan eşyalar",
    defaultDescEN: "Found items",
  },
  {
    id: "lost-found-hq",
    route: "/kayip-esya-hq",
    icon: Briefcase,
    group: "operations",
    order: 18,
    labelKey: "nav.lostFound",
    defaultLabelTR: "Kayıp Eşya",
    defaultLabelEN: "Lost & Found",
    scopes: ["hq"],
    color: "bg-yellow-600",
    descriptionKey: "nav.desc.lostFound",
    defaultDescTR: "Bulunan eşyalar",
    defaultDescEN: "Found items",
  },
  {
    id: "shifts",
    route: "/vardiyalar",
    icon: Calendar,
    group: "operations",
    order: 20,
    labelKey: "nav.shifts",
    defaultLabelTR: "Vardiyalar",
    defaultLabelEN: "Shifts",
    scopes: ["branch", "hq"],
    color: "bg-purple-500",
    bgColor: "bg-cyan-100 dark:bg-cyan-900/40",
    descriptionKey: "nav.desc.shifts",
    defaultDescTR: "Çalışma saatleri",
    defaultDescEN: "Work schedules",
  },
  {
    id: "myshifts",
    route: "/vardiyalarim",
    icon: Clock,
    group: "operations",
    order: 21,
    labelKey: "nav.myShifts",
    defaultLabelTR: "Vardiyam",
    defaultLabelEN: "My Shifts",
    scopes: ["branch", "factory"],
    descriptionKey: "nav.desc.myShifts",
    defaultDescTR: "Kendi vardiyalarım",
    defaultDescEN: "My shift schedule",
  },
  {
    id: "support",
    route: "/hq-destek",
    icon: MessageSquare,
    group: "operations",
    order: 25,
    labelKey: "nav.support",
    defaultLabelTR: "Merkez Destek",
    defaultLabelEN: "HQ Support",
    scopes: ["branch", "hq"],
    color: "bg-blue-500",
    descriptionKey: "nav.desc.support",
    defaultDescTR: "HQ'ya talep gönder",
    defaultDescEN: "Send request to HQ",
  },
  {
    id: "notifications",
    route: "/bildirimler",
    icon: Bell,
    group: "operations",
    order: 28,
    labelKey: "nav.notifications",
    defaultLabelTR: "Bildirimler",
    defaultLabelEN: "Notifications",
    scopes: ["branch", "hq", "factory"],
  },
  {
    id: "academy",
    route: "/akademi",
    icon: GraduationCap,
    group: "management",
    order: 30,
    labelKey: "nav.academy",
    defaultLabelTR: "Akademi",
    defaultLabelEN: "Academy",
    scopes: ["branch"],
    color: "bg-blue-500",
    bgColor: "bg-indigo-100 dark:bg-indigo-900/40",
    descriptionKey: "nav.desc.academy",
    defaultDescTR: "Eğitim & Gelişim",
    defaultDescEN: "Training & Development",
    getRoute: (user) => {
      const hqRoles = ["ceo", "cgo", "admin", "muhasebe", "muhasebe_ik", "satinalma", "marketing", "pazarlama", "teknik", "destek", "trainer", "coach", "kalite_kontrol", "fabrika_mudur", "fabrika", "yatirimci_hq", "ekipman_teknik", "ik"];
      return hqRoles.includes(user?.role) ? "/akademi-hq" : "/akademi";
    },
  },
  {
    id: "academy-hq",
    route: "/yonetim/akademi",
    icon: GraduationCap,
    group: "management",
    order: 30,
    labelKey: "nav.academyHQ",
    defaultLabelTR: "Akademi Yönetimi",
    defaultLabelEN: "Academy Management",
    scopes: ["hq"],
    color: "bg-blue-500",
    descriptionKey: "nav.desc.academyHQ",
    defaultDescTR: "Eğitim yönetimi",
    defaultDescEN: "Training management",
  },
  {
    id: "hr",
    route: "/ik",
    icon: Users,
    group: "management",
    order: 35,
    labelKey: "nav.hr",
    defaultLabelTR: "İK",
    defaultLabelEN: "HR",
    scopes: ["branch", "hq"],
    color: "bg-pink-500",
    bgColor: "bg-pink-100 dark:bg-pink-900/40",
    descriptionKey: "nav.desc.hr",
    defaultDescTR: "Personel yönetimi",
    defaultDescEN: "Personnel management",
  },
  {
    id: "leaves",
    route: "/izin-talepleri",
    icon: CalendarDays,
    group: "management",
    order: 36,
    labelKey: "nav.leaves",
    defaultLabelTR: "İzin Talebi",
    defaultLabelEN: "Leave Request",
    scopes: ["branch", "hq"],
    bgColor: "bg-teal-100 dark:bg-teal-900/40",
  },
  {
    id: "branches",
    route: "/subeler",
    icon: Building2,
    group: "management",
    order: 40,
    labelKey: "nav.branches",
    defaultLabelTR: "Şubeler",
    defaultLabelEN: "Branches",
    scopes: ["hq"],
    color: "bg-indigo-500",
    descriptionKey: "nav.desc.branches",
    defaultDescTR: "Şube yönetimi",
    defaultDescEN: "Branch management",
  },
  {
    id: "reports",
    route: "/e2e-raporlar",
    icon: BarChart3,
    group: "management",
    order: 45,
    labelKey: "nav.reports",
    defaultLabelTR: "Raporlar",
    defaultLabelEN: "Reports",
    scopes: ["hq", "branch"],
    color: "bg-cyan-500",
    bgColor: "bg-slate-100 dark:bg-slate-900/40",
    descriptionKey: "nav.desc.reports",
    defaultDescTR: "Analitik & PDF export",
    defaultDescEN: "Analytics & PDF export",
    getRoute: (user) => {
      const branchRoles = ["mudur", "supervisor", "supervisor_buddy", "barista", "bar_buddy", "stajyer", "yatirimci_branch"];
      return branchRoles.includes(user?.role) ? "/raporlar" : "/e2e-raporlar";
    },
  },
  {
    id: "quality",
    route: "/kalite-denetimi",
    icon: Star,
    group: "management",
    order: 47,
    labelKey: "nav.quality",
    defaultLabelTR: "Kalite Kontrol",
    defaultLabelEN: "Quality Control",
    scopes: ["hq"],
    color: "bg-amber-500",
    descriptionKey: "nav.desc.quality",
    defaultDescTR: "Kalite & denetim",
    defaultDescEN: "Quality & auditing",
  },
  {
    id: "performance",
    route: "/performans",
    icon: BarChart3,
    group: "management",
    order: 48,
    labelKey: "nav.performance",
    defaultLabelTR: "Performans",
    defaultLabelEN: "Performance",
    scopes: ["branch"],
    roles: ["supervisor", "supervisor_buddy", "yatirimci_branch", "admin"],
    color: "bg-cyan-500",
    descriptionKey: "nav.desc.performance",
    defaultDescTR: "Performans metrikleri",
    defaultDescEN: "Performance metrics",
  },
  {
    id: "knowledge",
    route: "/bilgi-bankasi",
    icon: BookOpen,
    group: "management",
    order: 49,
    labelKey: "nav.knowledge",
    defaultLabelTR: "Bilgi Bankası",
    defaultLabelEN: "Knowledge Base",
    scopes: ["branch", "hq"],
    color: "bg-emerald-500",
    descriptionKey: "nav.desc.knowledge",
    defaultDescTR: "Dokümanlar & rehberler",
    defaultDescEN: "Documents & guides",
  },
  {
    id: "factory",
    route: "/fabrika",
    icon: Factory,
    group: "operations",
    order: 22,
    labelKey: "nav.factory",
    defaultLabelTR: "Fabrika",
    defaultLabelEN: "Factory",
    scopes: ["factory", "hq"],
    color: "bg-orange-500",
    bgColor: "bg-orange-100 dark:bg-orange-900/40",
    descriptionKey: "nav.desc.factory",
    defaultDescTR: "Üretim yönetimi",
    defaultDescEN: "Production management",
  },
  {
    id: "muhasebe",
    route: "/muhasebe",
    icon: Calculator,
    group: "management",
    order: 50,
    labelKey: "nav.accounting",
    defaultLabelTR: "Muhasebe",
    defaultLabelEN: "Accounting",
    scopes: ["hq"],
    roles: ["admin", "muhasebe", "muhasebe_ik"],
    color: "bg-emerald-600",
    descriptionKey: "nav.desc.accounting",
    defaultDescTR: "Bordro & Maaş Yönetimi",
    defaultDescEN: "Payroll & Salary",
  },
  {
    id: "stock",
    route: "/satinalma",
    icon: Package,
    group: "management",
    order: 52,
    labelKey: "nav.stock",
    defaultLabelTR: "Stok",
    defaultLabelEN: "Stock",
    scopes: ["hq"],
    bgColor: "bg-amber-100 dark:bg-amber-900/40",
    descriptionKey: "nav.desc.stock",
    defaultDescTR: "Satınalma & stok",
    defaultDescEN: "Procurement & stock",
  },
  {
    id: "projects",
    route: "/projeler",
    icon: FolderKanban,
    group: "management",
    order: 55,
    labelKey: "nav.projects",
    defaultLabelTR: "Projeler",
    defaultLabelEN: "Projects",
    scopes: ["hq"],
    color: "bg-violet-600",
    descriptionKey: "nav.desc.projects",
    defaultDescTR: "HQ Proje Yönetimi",
    defaultDescEN: "HQ Project Management",
  },
  {
    id: "live-tracking",
    route: "/canli-takip",
    icon: MapPin,
    group: "management",
    order: 56,
    labelKey: "nav.liveTracking",
    defaultLabelTR: "Canlı Takip",
    defaultLabelEN: "Live Tracking",
    scopes: ["branch", "hq"],
    roles: ["supervisor", "manager", "admin", "ceo", "cgo"],
    color: "bg-emerald-500",
    descriptionKey: "nav.desc.liveTracking",
    defaultDescTR: "Personel konum takibi",
    defaultDescEN: "Staff location tracking",
  },
  {
    id: "crm",
    route: "/crm",
    icon: Headphones,
    group: "management",
    order: 57,
    labelKey: "nav.crm",
    defaultLabelTR: "CRM",
    defaultLabelEN: "CRM",
    scopes: ["hq"],
    color: "bg-rose-500",
    descriptionKey: "nav.desc.crm",
    defaultDescTR: "Franchise Destek Merkezi",
    defaultDescEN: "Franchise Support Center",
    getRoute: (user) => {
      if (!user) return "/crm";
      switch (user.role) {
        case "coach": return "/crm/coach-branches";
        case "satinalma": return "/crm/tedarikciler";
        case "muhasebe":
        case "muhasebe_ik": return "/crm/cari-takip";
        case "teknik":
        case "ekipman_teknik": return "/crm/teknik-ariza";
        case "trainer": return "/crm/dashboard";
        default: return "/crm";
      }
    },
  },
  {
    id: "announcements",
    route: "/admin/duyurular",
    icon: Megaphone,
    group: "settings",
    order: 60,
    labelKey: "nav.announcements",
    defaultLabelTR: "Duyurular",
    defaultLabelEN: "Announcements",
    scopes: ["hq"],
    color: "bg-red-500",
    bgColor: "bg-rose-100 dark:bg-rose-900/40",
    descriptionKey: "nav.desc.announcements",
    defaultDescTR: "Duyuru yönetimi",
    defaultDescEN: "Announcement management",
  },
  {
    id: "ai-assistant",
    route: "/ai-asistan",
    icon: Bot,
    group: "settings",
    order: 62,
    labelKey: "nav.aiAssistant",
    defaultLabelTR: "AI Asistan",
    defaultLabelEN: "AI Assistant",
    scopes: ["hq", "branch"],
    color: "bg-violet-500",
    descriptionKey: "nav.desc.aiAssistant",
    defaultDescTR: "Yapay zeka asistanı",
    defaultDescEN: "AI assistant",
    getRoute: (user) => {
      if (user?.role === "ceo") return "/ceo-command-center";
      if (user?.role === "cgo") return "/cgo-command-center";
      return "/ai-asistan";
    },
  },
  {
    id: "users",
    route: "/yonetim/kullanicilar",
    icon: Users,
    group: "settings",
    order: 65,
    labelKey: "nav.users",
    defaultLabelTR: "Kullanıcılar",
    defaultLabelEN: "Users",
    scopes: ["hq"],
    color: "bg-sky-500",
    descriptionKey: "nav.desc.users",
    defaultDescTR: "Kullanıcı yönetimi",
    defaultDescEN: "User management",
  },
  {
    id: "admin-settings",
    route: "/yonetim/ayarlar",
    icon: Settings,
    group: "settings",
    order: 68,
    labelKey: "nav.adminSettings",
    defaultLabelTR: "Yönetim",
    defaultLabelEN: "Admin Settings",
    scopes: ["hq"],
    color: "bg-slate-600",
    descriptionKey: "nav.desc.adminSettings",
    defaultDescTR: "Sistem ayarları",
    defaultDescEN: "System settings",
  },
  {
    id: "admin-panel",
    route: "/admin",
    icon: Shield,
    group: "settings",
    order: 70,
    labelKey: "nav.adminPanel",
    defaultLabelTR: "Admin Panel",
    defaultLabelEN: "Admin Panel",
    scopes: ["hq"],
    roles: ["admin"],
    color: "bg-red-600",
    descriptionKey: "nav.desc.adminPanel",
    defaultDescTR: "Sistem yönetimi",
    defaultDescEN: "System administration",
  },
  {
    id: "bulk-data",
    route: "/admin/toplu-veri-yonetimi",
    icon: Database,
    group: "settings",
    order: 72,
    labelKey: "nav.bulkData",
    defaultLabelTR: "Toplu Veri Yönetimi",
    defaultLabelEN: "Bulk Data Management",
    scopes: ["hq"],
    roles: ["admin"],
    color: "bg-indigo-600",
    descriptionKey: "nav.desc.bulkData",
    defaultDescTR: "Excel ile veri aktarımı",
    defaultDescEN: "Data import via Excel",
  },
  {
    id: "search",
    route: "#search",
    icon: Search,
    group: "operations",
    order: 99,
    labelKey: "nav.search",
    defaultLabelTR: "Ara",
    defaultLabelEN: "Search",
    scopes: ["branch", "hq", "factory"],
    isSearch: true,
  },
  {
    id: "profile",
    route: "/login",
    icon: User,
    group: "settings",
    order: 100,
    labelKey: "nav.profile",
    defaultLabelTR: "Profil",
    defaultLabelEN: "Profile",
    scopes: ["branch", "hq", "factory"],
    getRoute: (user) => user ? `/personel/${user.id}` : "/login",
  },
  {
    id: "new-task",
    route: "/gorevler?new=true",
    icon: ClipboardList,
    group: "operations",
    order: 9,
    labelKey: "nav.newTask",
    defaultLabelTR: "Yeni Görev",
    defaultLabelEN: "New Task",
    scopes: ["branch", "hq"],
    bgColor: "bg-blue-100 dark:bg-blue-900/40",
  },
  {
    id: "production",
    route: "/fabrika",
    icon: Factory,
    group: "operations",
    order: 23,
    labelKey: "nav.production",
    defaultLabelTR: "Üretim",
    defaultLabelEN: "Production",
    scopes: ["factory"],
    bgColor: "bg-orange-100 dark:bg-orange-900/40",
  },
  {
    id: "suppliers",
    route: "/satinalma",
    icon: Store,
    group: "management",
    order: 53,
    labelKey: "nav.suppliers",
    defaultLabelTR: "Tedarikçiler",
    defaultLabelEN: "Suppliers",
    scopes: ["hq"],
    bgColor: "bg-teal-100 dark:bg-teal-900/40",
  },
  {
    id: "goods-receipt",
    route: "/satinalma?tab=mal-kabul",
    icon: ClipboardCheck,
    group: "management",
    order: 54,
    labelKey: "nav.goodsReceipt",
    defaultLabelTR: "Mal Kabul",
    defaultLabelEN: "Goods Receipt",
    scopes: ["hq"],
  },
  {
    id: "orders",
    route: "/satinalma?tab=siparisler",
    icon: ShoppingCart,
    group: "management",
    order: 51,
    labelKey: "nav.orders",
    defaultLabelTR: "Siparişler",
    defaultLabelEN: "Orders",
    scopes: ["hq"],
    bgColor: "bg-green-100 dark:bg-green-900/40",
  },
  {
    id: "campaigns",
    route: "/admin",
    icon: Megaphone,
    group: "settings",
    order: 61,
    labelKey: "nav.campaigns",
    defaultLabelTR: "Kampanyalar",
    defaultLabelEN: "Campaigns",
    scopes: ["hq"],
    bgColor: "bg-fuchsia-100 dark:bg-fuchsia-900/40",
  },
  {
    id: "courses",
    route: "/akademi",
    icon: GraduationCap,
    group: "management",
    order: 31,
    labelKey: "nav.courses",
    defaultLabelTR: "Kurslar",
    defaultLabelEN: "Courses",
    scopes: ["hq"],
    bgColor: "bg-indigo-100 dark:bg-indigo-900/40",
  },
  {
    id: "audits",
    route: "/raporlar/denetimler",
    icon: ClipboardList,
    group: "management",
    order: 46,
    labelKey: "nav.audits",
    defaultLabelTR: "Denetim",
    defaultLabelEN: "Audits",
    scopes: ["hq"],
    bgColor: "bg-amber-100 dark:bg-amber-900/40",
  },
  {
    id: "invoices",
    route: "/raporlar",
    icon: FileText,
    group: "management",
    order: 50,
    labelKey: "nav.invoices",
    defaultLabelTR: "Faturalar",
    defaultLabelEN: "Invoices",
    scopes: ["hq"],
    bgColor: "bg-cyan-100 dark:bg-cyan-900/40",
  },
  {
    id: "attendance",
    route: "/ik",
    icon: Users,
    group: "management",
    order: 37,
    labelKey: "nav.attendance",
    defaultLabelTR: "Devam",
    defaultLabelEN: "Attendance",
    scopes: ["hq"],
    bgColor: "bg-rose-100 dark:bg-rose-900/40",
  },
  {
    id: "maintenance",
    route: "/ekipman",
    icon: Wrench,
    group: "operations",
    order: 17,
    labelKey: "nav.maintenance",
    defaultLabelTR: "Bakım",
    defaultLabelEN: "Maintenance",
    scopes: ["hq"],
    bgColor: "bg-yellow-100 dark:bg-yellow-900/40",
  },
  {
    id: "ai-dashboard",
    route: "/raporlar/ai-asistan",
    icon: Bot,
    group: "settings",
    order: 63,
    labelKey: "nav.aiDashboard",
    defaultLabelTR: "AI Panel",
    defaultLabelEN: "AI Dashboard",
    scopes: ["hq"],
    bgColor: "bg-purple-100 dark:bg-purple-900/40",
  },
  {
    id: "calendar",
    route: "/vardiya-planlama",
    icon: CalendarDays,
    group: "operations",
    order: 22,
    labelKey: "nav.calendar",
    defaultLabelTR: "Takvim",
    defaultLabelEN: "Calendar",
    scopes: ["hq"],
  },
];

export function getNavItemById(id: string): NavItem | undefined {
  return NAV_ITEMS.find((item) => item.id === id);
}

export function getNavItemsByIds(ids: string[]): NavItem[] {
  return ids.map((id) => NAV_ITEMS.find((item) => item.id === id)).filter(Boolean) as NavItem[];
}

export function getNavItemRoute(item: NavItem, user: any): string {
  if (item.getRoute) return item.getRoute(user);
  return item.route;
}

export function resolveNavLabel(
  item: { labelKey: string; defaultLabelTR: string; defaultLabelEN: string },
  t?: (key: string, options?: any) => string,
  lang?: string
): string {
  if (t) {
    return t(item.labelKey, { defaultValue: lang === "en" ? item.defaultLabelEN : item.defaultLabelTR });
  }
  return lang === "en" ? item.defaultLabelEN : item.defaultLabelTR;
}

export function resolveNavDescription(
  item: NavItem,
  t?: (key: string, options?: any) => string,
  lang?: string
): string {
  if (!item.descriptionKey) return "";
  if (t) {
    return t(item.descriptionKey, { defaultValue: lang === "en" ? (item.defaultDescEN || "") : (item.defaultDescTR || "") });
  }
  return lang === "en" ? (item.defaultDescEN || "") : (item.defaultDescTR || "");
}
