import { Router } from "express";
import { db } from "../db";
import { isAuthenticated } from "../localAuth";
import { eq, and, sql, desc, gte, lte, isNull } from "drizzle-orm";
import { tasks, taskTriggers } from "@shared/schema";
import { generateTasksForUser } from "../services/task-trigger-service";
import { createAuditEntry, getAuditContext } from "../audit";

const router = Router();

router.get("/api/action-cards/today", isAuthenticated, async (req, res) => {
  try {
    const userId = (req.user as any)?.id;
    if (!userId) return res.status(401).json({ error: "Unauthorized" });

    const nowTR = new Date(new Date().toLocaleString("en-US", { timeZone: "Europe/Istanbul" }));
    const todayStart = new Date(nowTR.getFullYear(), nowTR.getMonth(), nowTR.getDate());
    const todayEnd = new Date(todayStart.getTime() + 24 * 60 * 60 * 1000);

    const todayCards = await db
      .select({
        id: tasks.id,
        description: tasks.description,
        status: tasks.status,
        priority: tasks.priority,
        requiresPhoto: tasks.requiresPhoto,
        photoUrl: tasks.photoUrl,
        dueDate: tasks.dueDate,
        triggerId: tasks.triggerId,
        occurrenceKey: tasks.occurrenceKey,
        autoGenerated: tasks.autoGenerated,
        evidenceType: tasks.evidenceType,
        evidenceData: tasks.evidenceData,
        completedAt: tasks.completedAt,
        createdAt: tasks.createdAt,
        triggerName: taskTriggers.name,
        triggerTemplate: taskTriggers.template,
      })
      .from(tasks)
      .leftJoin(taskTriggers, eq(tasks.triggerId, taskTriggers.id))
      .where(and(
        eq(tasks.assignedToId, userId),
        eq(tasks.autoGenerated, true),
        gte(tasks.createdAt, todayStart),
        lte(tasks.createdAt, todayEnd),
        isNull(tasks.deletedAt)
      ))
      .orderBy(desc(tasks.createdAt));

    const enriched = todayCards.map((card) => {
      let template: any = {};
      try {
        template = card.triggerTemplate ? JSON.parse(card.triggerTemplate) : {};
      } catch {}
      return {
        ...card,
        title: template.title || card.triggerName || card.description,
        tags: template.tags || [],
      };
    });

    return res.json(enriched);
  } catch (error: any) {
    console.error("[ActionCards] Error fetching today:", error);
    return res.status(500).json({ error: "Görevler yüklenemedi" });
  }
});

router.post("/api/action-cards/:id/submit", isAuthenticated, async (req, res) => {
  try {
    const userId = (req.user as any)?.id;
    if (!userId) return res.status(401).json({ error: "Unauthorized" });

    const taskId = parseInt(req.params.id);
    if (isNaN(taskId)) return res.status(400).json({ error: "Geçersiz görev ID" });

    const [task] = await db
      .select()
      .from(tasks)
      .where(and(
        eq(tasks.id, taskId),
        eq(tasks.assignedToId, userId),
        eq(tasks.autoGenerated, true),
        isNull(tasks.deletedAt)
      ))
      .limit(1);

    if (!task) return res.status(404).json({ error: "Görev bulunamadı" });

    const { evidenceType: submitType, evidenceData, photoUrl, notes } = req.body;

    const updateData: any = {
      status: "incelemede",
      updatedAt: new Date(),
      completedAt: new Date(),
    };

    if (submitType === "photo" && photoUrl) {
      updateData.photoUrl = photoUrl;
      updateData.evidenceData = JSON.stringify({ type: "photo", url: photoUrl, notes });
    } else if (submitType === "form" && evidenceData) {
      updateData.evidenceData = JSON.stringify({ type: "form", data: evidenceData, notes });
    } else if (submitType === "approval") {
      updateData.evidenceData = JSON.stringify({ type: "approval", notes });
      updateData.status = "onaylandi";
    } else if (submitType === "none") {
      updateData.status = "onaylandi";
    }

    await db
      .update(tasks)
      .set(updateData)
      .where(eq(tasks.id, taskId));

    try {
      await createAuditEntry(getAuditContext(req), {
        eventType: "task.action_card_submitted",
        action: "submit",
        resource: "action_card",
        resourceId: String(taskId),
        details: { evidenceType: submitType, triggerId: task.triggerId },
      });
    } catch {}

    return res.json({ success: true, message: "Kanıt gönderildi" });
  } catch (error: any) {
    console.error("[ActionCards] Error submitting:", error);
    return res.status(500).json({ error: "Gönderilemedi" });
  }
});

router.post("/api/action-cards/generate", isAuthenticated, async (req, res) => {
  try {
    const userId = (req.user as any)?.id;
    if (!userId) return res.status(401).json({ error: "Unauthorized" });

    const result = await generateTasksForUser(userId);
    return res.json(result);
  } catch (error: any) {
    console.error("[ActionCards] Error generating:", error);
    return res.status(500).json({ error: "Oluşturulamadı" });
  }
});

router.get("/api/task-triggers", isAuthenticated, async (req, res) => {
  try {
    const triggers = await db.select().from(taskTriggers).orderBy(taskTriggers.roleCode);
    return res.json(triggers);
  } catch (error: any) {
    console.error("[TaskTriggers] Error fetching:", error);
    return res.status(500).json({ error: "Trigger listesi yüklenemedi" });
  }
});

export default router;
